name: chat-service

services:
  postgres:
    image: postgres:16
    container_name: chat-service-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5426:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d support"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
    name: diplom_chat_service_postgres_data